### PR TITLE
12561 e2o optional fix

### PR DESCRIPTION
**Pull request by NinjaManatee**
**Resolves issue [12561](https://chartiq.kanbanize.com/ctrl_board/18/cards/12561/details)**

**Description of change**
- Check whether e2o exists before requiring it in.

**Description of testing**

1. Clean check out of seed
1. Remove e2o as an optional dependency so it doesn't get installed
1. `npm i`
1. `npm run dev`
1. observer that finsemble runs even if e2o is not installed.

### CODE REVIEW

**Comment by amaroks** [comment]
@htonus This PR fixes the problem you faced when running the seed with openfin :)

**Comment by NinjaManatee** [comment]
@htonus This PR is out of date now. The dependencies have changed, and so has the gulpfile.

**Comment by NinjaManatee** [comment]
@htonus I updated the branch from develop, and fixed it so it will work without FEA.

**Comment by carterbs** [comment]
Rebased onto epic/3.8

**Pull request merged**
