### PR TITLE
feat: #id 22750 wrap app launcher and advanced app launcher

### PR DESCRIPTION
**Pull request by meredith-ciq**
Requires: https://github.com/ChartIQ/finsemble-ui/pull/22

[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22750/details)

**Description of change**
* See https://github.com/ChartIQ/finsemble-ui/pull/22
The css files in app.jsx were files that we did not want to move to finsemble-ui for now. They reference many different font files that would need to be moved over.

### CODE REVIEW

**Comment by amaroks** [comment]
Can you merge seed-refactor into your branch?

**Comment by meredith-ciq** [comment]
There is nothing to merge.

**Comment by amaroks** [comment]
Weird, why do we see others commit?
`zona-ciq and others added 30 commits 22 days ago`

**Comment by meredith-ciq** [comment]
I'm pretty sure I had to branch off one of the teams branches because menuing wasn't done yet. I've done all kinds of rebases and merges since then.

**Pull request merged**
