### PR TITLE
Gulp refactor 2

### PR DESCRIPTION
**Pull request by erik-ciq**
**There were three main goals in this PR.**

- [x] Replace callbacks with async / await 
- [x] Modularize the code
- [x] Increase readability, maintainability, and remove redundancy

**New modules were created:**

- [x] `gulpfile.js/buildSass` - Still a stub just like before
- [x] `gulpfile.js/envOrArg` 
- [x] `gulpfile.js/getFinsembleLinks` - returns objects with { path, name, version } for finsemble dependencies
- [x] `gulpfile.js/index.js` `gulpfile.js` -> `gulpfile.js/index.js` per gulp docs
- [x] `gulpfile.js/launchApplication` handles launching openfin or e20
- [x] `gulpfile.js/listableExecute` consumes an array of commands and runs them
- [x] `gulpfile.js/logToTerminal` one of the most heavily used functions I saw
- [x] `gulpfile.jssafeRequire` runs stat before requiring a module, abstracted to keep things DRY
- [x] `gulpfile.js/startServer` handles running the server
- [x] `gulpfile.js/tasks` composable tasks for gulp, more depth on this below
- [x] `gulpfile.js/verifyLinks.js` checks provided links, throws errors if they are missing
- [x] `./buildAngular.js` handles any angular work
- [x] `./buildWebpack.js` handles any webpack work

**Tasks:**
Tried to unify the atomic tasks that were being used. Pulled them into their own functions for re-usability and composition.

- [x] `pre`
- [x] `post`
- [x] `clean`
- [x] `build`  requires an `environment` arg
- [x] `serve` requires an `environment` arg
- [x] `launch` requires a `channelAdapter` and `manifest`
- [x] `buildServe` combines `build` and `serve`, requires an `environment` arg
- [x] `buildServeLaunch` combines `build`, `serve`, and `launch`, requires `environment` arg
- [x] `rebuildServeLaunch` combines `clean`, `build`, `serve`, and `launch`, requires `environment` arg
- [x] `rebuild` combines `clean` and `build`, requires `environment` arg
- [x] `serveLaunch` combines `serve` and `launch`, requires `environment` arg

**Description of testing**

- [x] Ensure running gulp tasks still works
- [ ] Test with extensions
- [ ] Test with angular configuration

I'd really like to update our gulpfile-extensions file as well if possible. Also curious to know if I can update any usages of this in the wild, my understanding is one of our customers uses this file. If I can update usages in the wild, I can unify things even more.

Would love to convert this to `.ts` and use interfaces to ensure we have tasks being called correctly. Maybe in a subsequent PR.

### CODE REVIEW

**Comment by erik-ciq** [comment]
- [ ] clean task should wipe the .`/dist` folder
- [ ] prod:nolaunch never exits
- [ ] prod:noLaunch doesn't rebuild when a file changes (should watch)
- [ ] server and server:prod fail 
- [ ] move `./buildWebpack` to build folder
- [ ] move `./buildAngular` to build folder
- [ ] figure out solution for `./buildSass`
- [ ] update filename of `launche20`

**Comment by erik-ciq** [comment]
We really need to add command line flags here:

`--environment`: `development` or `production`, defaults to `development`
`--watch`: `true` or `false`, defaults to `false`

I'll create a kanbanize card for this.

**Comment by d4hines** [comment]
> it does not seem to exit on master either...
> it does not rebuild on master...

I don't doubt it, and I was just confused about the tasks' respective purposes. If @NinjaManatee can confirm they're still needed (I've never seen anyone on our team use them), then let's comment them with some their purpose and usage. Otherwise, let's cut them.

**Comment by NinjaManatee** [comment]
prod:noLaunch should start the server so you can launch Finsemble from a link, but it shouldn't start Finsemble automatically. It should not exit because the server is still running.

None of the prod tasks should watch because watching and rebuilding is a dev operation. 

@d4hines @erik-ciq

**Pull request closed without merging**
