### PR TITLE
feat: #id 16100 enable chrome remote debugging in production mode

### PR DESCRIPTION
**Pull request by zona-ciq**
feat: #id [16100]

[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16100/details/)

**Description of change**
* add in chrome remote debugging flag to the default production configuration

**Description of testing**
1. Pull down this branch
1. Run `npm run makeInstaller:prod` in the seed, after it finishes, run `npm run server` in the seed terminal
1. [x] Launch the installer, after Finsemble comes up, go to http://localhost:9222/ and check out the debugging window for different finsemble components

### CODE REVIEW

**Comment by zona-ciq** [comment]
> Following your steps, http://localhost:9222/ is unreachable after running installer and server.

Are you linked to 3.13.0 for FEA and Finsemble Core?

**Comment by amaroks** [comment]
@zona-ciq yes double checked

**Comment by carterbs** [comment]
@amaroks I got this to work.

I had to fight like hell to get the installer working. Turns out I had some files from 4.0.0 on my hard drive. Make sure that you did `npm run makeInstaller:prod` and not `npm run makeInstaller:dev`. Also, delete the `finsemble` folder in `finsemble-seed`. Then run `npm run dev:nolaunch`. This will recopy finsemble from node_modules. If you've been switching between 4.0.0 and 3.13, there's a chance that folder got corrupted. I'm approving this. Let me know if you want to try it together.

**Comment by amaroks** [comment]
I tried one more time, checked out branches, installed and linked. Deleted finsemble, followed @carterbs suggestion to copy finsemble again etc. Still does not work for me.

**Pull request merged**
