### PR TITLE
[14990] process monitor collapse feature

### PR DESCRIPTION
**Pull request by sonyl-ciq**
**feat 14990**

[Kanban link](https://chartiq.kanbanize.com/ctrl_board/21/cards/14990/details/)

> We should add a way to collapse the each grouping so you only see the groupings name, CPU, Memory, Peak Memory, PID and Terminate

> We should add the ability to export the process monitor information to CSV (ether as a file download or to the clipboard)

>> In conversation with @NinjaManatee , exporting as `json` was suggested as an alternative to CSV.

**Description of change**
* Changes:
  - Slight CSS changes
  - Placing `ChildWindows` into `ProcessStatistics` for ease of display/logic
  - Added Export Logs button to UI
  
  Oct-02-2019 09-28-50

**Description of testing**
1. Access Process Monitor.
1. Observe Arrows for collapsing/expanding the processes.
1. Use arrow in Simple mode.
    - [ ] Process collapses and expands
1. Trigger _Advanced_ with the button. 
1. Use arrow in Advanced mode on multiple processes, expanding and collapsing
    - [ ] Processes collapse and expand
1. Use _Export Data_ in Advanced mode to export a JSON file with relevant data
    - [ ] JSON file is downloaded listing all processes and their relevant details
1. Click a Terminate button
    - [ ] Process still terminates

### CODE REVIEW

**Comment by sonyl-ciq** [comment]
@NinjaManatee 

How does this look for you?

Screen Shot 2019-10-02 at 10 13 12 AM
Screen Shot 2019-10-02 at 10 13 30 AM
Screen Shot 2019-10-02 at 10 18 30 AM

**Comment by NinjaManatee** [comment]
Pretty print doesn't appear to work still, and the styling of the button is different:

image

When you click the button it has an underline. 

I know it is a nit, but I think it would look better if the "Export Data" button was closer to the Simple/Advanced button, and if the export data button was always visible.

**Comment by sonyl-ciq** [comment]
@NinjaManatee Here are the styling changes:

Screen Shot 2019-10-11 at 9 23 28 AM

However, when I export I do see the data formatted:

Screen Shot 2019-10-11 at 9 25 13 AM
Screen Shot 2019-10-11 at 9 24 15 AM

**Comment by sonyl-ciq** [comment]
Changing base as per @meredith-ciq . Will resolve conflicts.

**Comment by sonyl-ciq** [comment]
@NinjaManatee , I can tackle saving state next week. What is your thought on green lighting this work?

**Pull request closed without merging**
