### PR TITLE
Add globals.d.ts that sucks in type definition for FSBL

### PR DESCRIPTION
**Pull request by carterbs**

### CODE REVIEW

**Comment by kriswest** [comment]
:+1 for itellisense in seed, often requested! Particularly useful when docs
are not being updated as at present!

**Comment by carterbs** [comment]
@mesner not sure what to do with this. Looks like I reached out in Jan for a decision. Please decide whether to keep this open or to close it.

**Comment by mesner** [comment]
I thought this was already in as well.  I'd say merge.  It is one line.

**Comment by carterbs** [comment]
@mesner looked into it, and the mechanism that does this no longer works. It was to convert js to ts declaration files. all of our clients are TS now. so we'll need to go back to the drawing board to extract type definitions from our TS files.

**Pull request closed without merging**
