### PR TITLE
17089 Resolve URL against window.location

### PR DESCRIPTION
**Pull request by kriswest**
fix: #id [17089]

[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/17089/details)

**nativeOverrides should resolve URLs passed to it against window.location**
* Resolve the URL via the URL class before spawning a component with it

**Description of testing**
1. Add the nativeOverrides.js preload to the welcome component
```"preload": ["$applicationRoot/preloads/zoom.js", "$applicationRoot/preloads/nativeOverrides.js"]```
1. Spawn the component and in the JS console call: window.open("welcome.html");
1. Observe broken window is spawned.
1. repeat with modified preload and observe URL is correctly resolved.

### CODE REVIEW

**Comment by stephen-ciq** [comment]
i am looking at https://github.com/ChartIQ/finsemble-seed/pull/473
which is going to be merged into 4.1.0, so I merged 4.1.0 into it
and I cannot get the error that it is fixing to reproduce, even when following your instructions for "Description of testing"

GitHubGitHub
17089 Resolve URL against window.location by kriswest · Pull Request #473 · ChartIQ/finsemble-seed
fix: #id [17089] Kanban link nativeOverrides should resolve URLs passed to it against window.location Resolve the URL via the URL class before spawning a component with it Description of testing ...

i.e., regardless of whether "Welcome Component":"components":"preload" is ["$applicationRoot/preloads/zoom.js", "$applicationRoot/preloads/nativeOverrides.js"] or just the zoom.js file, calling window.open("welcome.html") works
so I'm not sure if this modification is no longer needed, or if I am missing something

**Comment by stephen-ciq** [comment]
@kriswest suggested that I try it on the 3.x line, which I can do.  However, this still doesn't necessarily indicate whether this code change is necessary in 4.1.0.  I believe it might be worth finding this out.  But maybe not.  I'd like input from @carterbs .

**Comment by meredith-ciq** [comment]
@stephen-ciq I get this issue on 4.1.0

**Comment by kriswest** [comment]
Ran a quick test video up for @stephen-ciq https://chartiq.slack.com/files/U8T1WPQ03/FQ0KXE35J/nativeoverridetest.mp4

**Comment by stephen-ciq** [comment]
For some odd reason I can get the previous behavior to reproduce this morning when I couldn't yesterday.

It might have had something to do with my install process, as I did a `rm -rf node_modules` this morning before trying again.  I apologize for the time that you had to spend on this -- looks good to go!  Thanks so much!

**Pull request merged**
